// <auto-generated />
using System;
using FormaGeo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormaGeo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FormaGeoDbContext))]
    [Migration("20260725232415_AddSuitabilityScoring")]
    partial class AddSuitabilityScoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormaGeo.Domain.Analyses.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("analysis_type");

                    b.Property<string>("AnalysisVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("analysis_version");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("InputParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_parameters");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("Status", "RequestedAtUtc");

                    b.ToTable("analysis_runs", (string)null);
                });

            modelBuilder.Entity("FormaGeo.Domain.Layers.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attribution");

                    b.Property<string>("LicenseName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("license_name");

                    b.Property<string>("LicenseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("license_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organization");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_url");

                    b.HasKey("Id");

                    b.ToTable("data_sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Attribution = "FormaGeo demonstration data — illustrative only",
                            LicenseName = "CC0 1.0",
                            LicenseUrl = "https://creativecommons.org/publicdomain/zero/1.0/",
                            Name = "FormaGeo contextual demonstration data",
                            Organization = "FormaGeo"
                        });
                });

            modelBuilder.Entity("FormaGeo.Domain.Layers.LayerDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<string>("CoordinateSystem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("coordinate_system");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("FeatureNameProperty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feature_name_property");

                    b.Property<string>("GeographicCoverage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("geographic_coverage");

                    b.Property<string>("GeometryType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("geometry_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("StyleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("style_json");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("IsActive");

                    b.ToTable("layer_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Category = "Boundaries",
                            CoordinateSystem = "EPSG:4326",
                            DataSourceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Illustrative administrative boundaries for testing overlay workflows.",
                            FeatureNameProperty = "name",
                            GeographicCoverage = "Metro Manila demonstration extent",
                            GeometryType = "Polygon",
                            IsActive = true,
                            Name = "Planning districts",
                            StyleJson = "{\"fillColor\":\"#6366f1\",\"strokeColor\":\"#3730a3\",\"strokeWidth\":2}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Category = "Planning",
                            CoordinateSystem = "EPSG:4326",
                            DataSourceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Illustrative generalized land-use areas for contextual analysis.",
                            FeatureNameProperty = "name",
                            GeographicCoverage = "Metro Manila demonstration extent",
                            GeometryType = "Polygon",
                            IsActive = true,
                            Name = "Land-use zones",
                            StyleJson = "{\"fillColor\":\"#f59e0b\",\"strokeColor\":\"#b45309\",\"strokeWidth\":1.5}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Category = "Hazards",
                            CoordinateSystem = "EPSG:4326",
                            DataSourceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Illustrative flood susceptibility areas; not suitable for risk decisions.",
                            FeatureNameProperty = "name",
                            GeographicCoverage = "Metro Manila demonstration extent",
                            GeometryType = "Polygon",
                            IsActive = true,
                            Name = "Flood susceptibility",
                            StyleJson = "{\"fillColor\":\"#0ea5e9\",\"strokeColor\":\"#0369a1\",\"strokeWidth\":1.5}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Category = "Environment",
                            CoordinateSystem = "EPSG:4326",
                            DataSourceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Illustrative environmental areas for testing planning overlays.",
                            FeatureNameProperty = "name",
                            GeographicCoverage = "Metro Manila demonstration extent",
                            GeometryType = "Polygon",
                            IsActive = true,
                            Name = "Green and protected areas",
                            StyleJson = "{\"fillColor\":\"#22c55e\",\"strokeColor\":\"#15803d\",\"strokeWidth\":1.5}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Category = "Transport",
                            CoordinateSystem = "EPSG:4326",
                            DataSourceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Illustrative transport links for testing line overlays.",
                            FeatureNameProperty = "name",
                            GeographicCoverage = "Metro Manila demonstration extent",
                            GeometryType = "LineString",
                            IsActive = true,
                            Name = "Primary transport corridors",
                            StyleJson = "{\"lineColor\":\"#ef4444\",\"lineWidth\":3}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Category = "Facilities",
                            CoordinateSystem = "EPSG:4326",
                            DataSourceId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Illustrative facility locations for testing point overlays and identification.",
                            FeatureNameProperty = "name",
                            GeographicCoverage = "Metro Manila demonstration extent",
                            GeometryType = "Point",
                            IsActive = true,
                            Name = "Community facilities",
                            StyleJson = "{\"circleColor\":\"#8b5cf6\",\"circleRadius\":7,\"strokeColor\":\"#ffffff\",\"strokeWidth\":2}"
                        });
                });

            modelBuilder.Entity("FormaGeo.Domain.Layers.LayerLegend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FillColor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("fill_color");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("LayerDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("layer_definition_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StrokeColor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("stroke_color");

                    b.Property<string>("Symbol")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("LayerDefinitionId", "SortOrder");

                    b.ToTable("layer_legends", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            FillColor = "#6366f1",
                            Label = "District boundary",
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000001"),
                            SortOrder = 0,
                            StrokeColor = "#3730a3"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            FillColor = "#f59e0b",
                            Label = "Mixed-use zone",
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000002"),
                            SortOrder = 0,
                            StrokeColor = "#b45309"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            FillColor = "#0ea5e9",
                            Label = "Moderate susceptibility",
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000003"),
                            SortOrder = 0,
                            StrokeColor = "#0369a1"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            FillColor = "#22c55e",
                            Label = "Green / protected area",
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000004"),
                            SortOrder = 0,
                            StrokeColor = "#15803d"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            FillColor = "#ef4444",
                            Label = "Primary corridor",
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000005"),
                            SortOrder = 0,
                            StrokeColor = "#991b1b"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            FillColor = "#8b5cf6",
                            Label = "Community facility",
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000006"),
                            SortOrder = 0,
                            StrokeColor = "#ffffff"
                        });
                });

            modelBuilder.Entity("FormaGeo.Domain.Layers.LayerVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DataUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("data_url");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("delivery_method");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<Guid>("LayerDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("layer_definition_id");

                    b.Property<int?>("MaximumZoom")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_zoom");

                    b.Property<int?>("MinimumZoom")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_zoom");

                    b.Property<string>("SourceLayer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_layer");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version_label");

                    b.HasKey("Id");

                    b.HasIndex("LayerDefinitionId", "IsCurrent");

                    b.ToTable("layer_versions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            DataUrl = "/layers/planning-districts.geojson",
                            DeliveryMethod = "GeoJson",
                            IsCurrent = true,
                            LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000001"),
                            VersionLabel = "2026.07-demo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            DataUrl = "/layers/land-use-zones.geojson",
                            DeliveryMethod = "GeoJson",
                            IsCurrent = true,
                            LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000002"),
                            VersionLabel = "2026.07-demo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            DataUrl = "/layers/flood-susceptibility.geojson",
                            DeliveryMethod = "GeoJson",
                            IsCurrent = true,
                            LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000003"),
                            VersionLabel = "2026.07-demo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            DataUrl = "/layers/green-areas.geojson",
                            DeliveryMethod = "GeoJson",
                            IsCurrent = true,
                            LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000004"),
                            VersionLabel = "2026.07-demo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            DataUrl = "/layers/transport-corridors.geojson",
                            DeliveryMethod = "GeoJson",
                            IsCurrent = true,
                            LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000005"),
                            VersionLabel = "2026.07-demo"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            DataUrl = "/layers/community-facilities.geojson",
                            DeliveryMethod = "GeoJson",
                            IsCurrent = true,
                            LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LayerDefinitionId = new Guid("20000000-0000-0000-0000-000000000006"),
                            VersionLabel = "2026.07-demo"
                        });
                });

            modelBuilder.Entity("FormaGeo.Domain.Layers.ProjectLayer", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("LayerDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("layer_definition_id");

                    b.Property<string>("Filter")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("filter");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<decimal>("Opacity")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("opacity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ProjectId", "LayerDefinitionId");

                    b.HasIndex("LayerDefinitionId");

                    b.HasIndex("ProjectId", "SortOrder");

                    b.ToTable("project_layers", (string)null);
                });

            modelBuilder.Entity("FormaGeo.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("FormaGeo.Domain.Scoring.ScoringCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("data_source");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("direction");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criterion_key");

                    b.Property<decimal>("LowerThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("lower_threshold");

                    b.Property<string>("MissingDataBehavior")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("missing_data_behavior");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizationMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("normalization_method");

                    b.Property<Guid>("ScoringModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_model_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UpperThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("upper_threshold");

                    b.Property<decimal>("Weight")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("ScoringModelId", "Key")
                        .IsUnique();

                    b.ToTable("scoring_criteria", (string)null);
                });

            modelBuilder.Entity("FormaGeo.Domain.Scoring.ScoringModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ScoringScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_scenario_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ScoringScenarioId", "Version")
                        .IsUnique();

                    b.ToTable("scoring_models", (string)null);
                });

            modelBuilder.Entity("FormaGeo.Domain.Scoring.ScoringResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at_utc");

                    b.Property<bool>("IsScoreable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_scoreable");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("overall_score");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rating");

                    b.Property<Guid>("ScoringModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_model_id");

                    b.Property<Guid>("ScoringScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_scenario_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("ScoringModelId");

                    b.HasIndex("SiteId");

                    b.HasIndex("ScoringScenarioId", "SiteId", "CalculatedAtUtc");

                    b.ToTable("scoring_results", (string)null);
                });

            modelBuilder.Entity("FormaGeo.Domain.Scoring.ScoringScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("scoring_scenarios", (string)null);
                });

            modelBuilder.Entity("FormaGeo.Domain.Sites.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<Polygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon,4326)")
                        .HasColumnName("boundary");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("ProjectId");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("FormaGeo.Domain.Analyses.AnalysisRun", b =>
                {
                    b.HasOne("FormaGeo.Domain.Sites.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormaGeo.Domain.Layers.LayerDefinition", b =>
                {
                    b.HasOne("FormaGeo.Domain.Layers.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("FormaGeo.Domain.Layers.LayerLegend", b =>
                {
                    b.HasOne("FormaGeo.Domain.Layers.LayerDefinition", null)
                        .WithMany("LegendItems")
                        .HasForeignKey("LayerDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormaGeo.Domain.Layers.LayerVersion", b =>
                {
                    b.HasOne("FormaGeo.Domain.Layers.LayerDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("LayerDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormaGeo.Domain.Layers.ProjectLayer", b =>
                {
                    b.HasOne("FormaGeo.Domain.Layers.LayerDefinition", null)
                        .WithMany()
                        .HasForeignKey("LayerDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormaGeo.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormaGeo.Domain.Scoring.ScoringCriterion", b =>
                {
                    b.HasOne("FormaGeo.Domain.Scoring.ScoringModel", null)
                        .WithMany("Criteria")
                        .HasForeignKey("ScoringModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormaGeo.Domain.Scoring.ScoringModel", b =>
                {
                    b.HasOne("FormaGeo.Domain.Scoring.ScoringScenario", null)
                        .WithMany()
                        .HasForeignKey("ScoringScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormaGeo.Domain.Scoring.ScoringResult", b =>
                {
                    b.HasOne("FormaGeo.Domain.Scoring.ScoringModel", null)
                        .WithMany()
                        .HasForeignKey("ScoringModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormaGeo.Domain.Scoring.ScoringScenario", null)
                        .WithMany()
                        .HasForeignKey("ScoringScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormaGeo.Domain.Sites.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormaGeo.Domain.Scoring.ScoringScenario", b =>
                {
                    b.HasOne("FormaGeo.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormaGeo.Domain.Sites.Site", b =>
                {
                    b.HasOne("FormaGeo.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormaGeo.Domain.Layers.LayerDefinition", b =>
                {
                    b.Navigation("LegendItems");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("FormaGeo.Domain.Scoring.ScoringModel", b =>
                {
                    b.Navigation("Criteria");
                });
#pragma warning restore 612, 618
        }
    }
}
